version: "3.8"
services:
  web:
    build: .
    container_name: web_front
    ports: 
      - "8000:8080"
    links:
      - mongo
    volumes:
      - .:/usr/src/app
    depends_on:
    - mongo

  mongo:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
