version: "3"
services:
  web:
    build: .
    ports: 
      - "7800:4200"
    links:
      - mongo
    volumes:
      - .:/usr/src/app
    depends_on:
    - mongo
  mongo:
    image: mongo
    ports:
      - "28017:27017"
