apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: az-mongo-disk
spec: 
  accessModes: 
  - ReadWriteOnce 
  storageClassName: default
  resources: 
    requests: 
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: backend
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: backend
    spec:
      containers:
      - image: mongo
        name: mongodb
        volumeMounts: 
        - mountPath: "/mnt/data" 
          name: mongodata
        ports: 
        - containerPort: 27017
        resources: {}
      volumes: 
      - name: mongodata
        persistentVolumeClaim: 
          claimName: az-mongo-disk
status: {}

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: backend
  name: backend
spec:
  ports:
  - port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    app: backend
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: frontend
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: frontend
    spec:
      containers:
      - image: burk1212/nodefrontend
        name: nodejs
        ports: 
        - containerPort: 8080
        resources: {}
status: {}

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: frontend
  name: frontend
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: frontend
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}